[package]
name = "kafka-uat"
version = "0.1.0"
authors = ["Michael Howard <michael.howard.h@gmail.com>"]
edition = "2018"

[dependencies]
kafka = "0.8"
crossbeam-channel = "0.4"
ctrlc = "3.1.3"
whoami = "0.7.0"
